apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-svc-tyk-stack-tyk-gateway
  name: gateway-svc-tyk-stack-tyk-gateway-nodeport
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30180
  selector:
    app: gateway-tyk-stack-tyk-gateway
