apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-control-svc-tyk-stack-tyk-gateway
  name: gateway-control-svc-tyk-stack-tyk-gateway-nodeport
spec:
  type: NodePort
  ports:
    - port: 9696
      protocol: TCP
      targetPort: 9696
      nodePort: 30181
  selector:
    app: gateway-tyk-stack-tyk-gateway
