apiVersion: v2
name: promtail
description: Deploy a full monitoring solution using the prometheues operator, grafana, promtail and loki
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: promtail
    alias: promtail
    version: 6.15.3
    repository: https://grafana.github.io/helm-charts
    condition: promtail.enabled
